import { readFile } from "node:fs/promises";

import type {
  ArmoryItem,
  CitationBackedText,
  Force,
  SourceCitation,
  UnitCard,
  UnitSpecialist,
  WeaponProfile,
} from "../../src/lib/types/domain";
import type { ForceAuditDatasetFile, ForceDatasetFile } from "../../src/lib/types/generated";

const UNIT_CARD_DOCUMENT_ID = "blkout-unit-cards-ocr";
const SCREENSHOT_DOCUMENT_ID = "blkout-unit-cards-screenshots";

interface ForceDatasetResult {
  forceDataset: ForceDatasetFile;
  auditDataset: ForceAuditDatasetFile;
}

export async function buildForceDataset(options: {
  filePath: string;
  generatedAt: string;
}): Promise<ForceDatasetResult> {
  const rawMarkdown = await readFile(options.filePath, "utf8");
  const lines = rawMarkdown.split(/\r?\n/);

  const force: Force = {
    id: "harlow-1st-reaction-force",
    cardId: "HFR-6770",
    name: "Harlow 1st Reaction Force",
    faction: "the-authority",
    battleDrills: [
      createTextRecord(
        "hfr-6770-battle-drill-assaulters",
        "Assaulters",
        "Models in this Unit cannot be Targeted by Overwatch when Repositioning.",
        [
          screenshotCitation("Force card battle drills", 2),
          ocrCitation(lines, "Assaulters: Models in this Unit cannot be Targeted by", "OCR battle drill cross-check"),
        ],
      ),
      createTextRecord(
        "hfr-6770-battle-drill-chaff",
        "Chaff",
        "Place a Smoke Token (Chaff) within 6\u201d of a Model in this Unit before Activating. Chaff Smoke Tokens Dissipate on a 10+.",
        [
          screenshotCitation("Force card battle drills", 2),
          ocrCitation(lines, "Chaff: Place a Smoke Token (Chaff) within 6\u201d", "OCR battle drill cross-check"),
        ],
      ),
      createTextRecord(
        "hfr-6770-battle-drill-stims",
        "Stims",
        "Models in this Unit gain +2 Movement for their Activation.",
        [
          screenshotCitation("Force card battle drills", 2),
          ocrCitation(lines, "Stims: Models in this Unit gain +2 Movement for their Activation.", "OCR battle drill cross-check"),
        ],
      ),
    ],
    rules: [
      createTextRecord(
        "hfr-6770-force-rule",
        "Harlow First Reaction Force",
        "Harlow First Reaction Force Units gain +2 Movement when Sprinting.",
        [
          screenshotCitation("Force card force rule", 2),
          ocrCitation(lines, "Harlow First Reaction Force Units gain +2 Movement", "OCR force rule cross-check"),
        ],
      ),
    ],
    armory: [
      createArmoryItem(
        "hfr-6770-armory-boost-jump",
        "BOOST JUMP",
        "gear",
        "UNKNOWN",
        "UNKNOWN",
        "Model gains Jump (4)",
        [screenshotCitation("Force card armory", 2), ocrCitation(lines, "BOOST JUMP", "OCR armory cross-check")],
      ),
      createArmoryItem(
        "hfr-6770-armory-frag-launcher",
        "FRAG LAUNCHER",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "Sustained (2), Medium",
        [screenshotCitation("Force card armory", 2), ocrCitation(lines, "FRAG LAUNCHER | 24”/1", "OCR armory cross-check")],
        createWeapon(
          "hfr-6770-armory-frag-launcher-profile",
          "Frag Launcher",
          "24\u201d/1",
          null,
          ["Sustained (2)", "Medium"],
          [screenshotCitation("Force card armory", 2)],
        ),
      ),
      createArmoryItem(
        "hfr-6770-armory-head",
        "HEAD",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "Blast (1)",
        [screenshotCitation("Force card armory", 2), ocrCitation(lines, "HEAD | 16”/4", "OCR armory cross-check")],
        createWeapon(
          "hfr-6770-armory-head-profile",
          "HEAD",
          "16\u201d/4",
          null,
          ["Blast (1)"],
          [screenshotCitation("Force card armory", 2)],
        ),
      ),
      createArmoryItem(
        "hfr-6770-armory-micro-launcher",
        "MICRO LAUNCHER",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "Blast (1), Heavy",
        [screenshotCitation("Force card armory", 2), ocrCitation(lines, "MICRO LAUNCHER | 4-16”/2", "OCR armory cross-check")],
        createWeapon(
          "hfr-6770-armory-micro-launcher-profile",
          "Micro Launcher",
          "4-16\u201d/2",
          null,
          ["Blast (1)", "Heavy"],
          [screenshotCitation("Force card armory", 2)],
        ),
      ),
    ],
    notes: [],
    citations: [screenshotCitation("Force card front", 1), screenshotCitation("Force card back", 2)],
    confidence: "verified",
  };
  const unRaidForceAlpha: Force = {
    id: "un-raid-force-alpha",
    cardId: "RFA-4390",
    name: "UN Raid Force Alpha",
    faction: "the-authority",
    battleDrills: [
      createTextRecord(
        "rfa-4390-battle-drill-close-assault",
        "Close Assault",
        "Models in this Unit may Move 2\u201d after their Activation ends, only if it would bring them into CQC with an Enemy Model.",
        [screenshotCitation("UN Raid Force Alpha force back", 14)],
      ),
      createTextRecord(
        "rfa-4390-battle-drill-cross-fire",
        "Cross Fire",
        "If more than one Model in this Unit Targets the same Enemy Model, their Weapons gain +1 Damage.",
        [screenshotCitation("UN Raid Force Alpha force back", 14)],
      ),
      createTextRecord(
        "rfa-4390-battle-drill-switchback",
        "Switchback",
        "Place a Smoke Token within 4\u201d of a Model in this Unit before Activating. All Models may be Moved up to 2\u201d before Activating.",
        [screenshotCitation("UN Raid Force Alpha force back", 14)],
      ),
    ],
    rules: [
      createTextRecord(
        "rfa-4390-force-rule",
        "UN Raid Team Alpha",
        "All UN Raid Team Alpha UTG Assaulter and Specialist Units gain an additional D10 roll in all Skill Checks, including Shooting and Close Quarters Combat (CQC).",
        [screenshotCitation("UN Raid Force Alpha force back", 14)],
      ),
    ],
    armory: [
      createArmoryItem("rfa-4390-armory-boost-jump", "BOOST JUMP", "gear", "UNKNOWN", "UNKNOWN", "Model gains Jump (6)", [screenshotCitation("UN Raid Force Alpha force back", 14)]),
      createArmoryItem(
        "rfa-4390-armory-lance",
        "LANCE",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "AP (3)",
        [screenshotCitation("UN Raid Force Alpha force back", 14)],
        createWeapon("rfa-4390-armory-lance-profile", "Lance", "12\u201d/1", null, ["AP (3)"], [screenshotCitation("UN Raid Force Alpha force back", 14)]),
      ),
      createArmoryItem(
        "rfa-4390-armory-micro-launcher",
        "MICRO LAUNCHER",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "Blast (1), Heavy",
        [screenshotCitation("UN Raid Force Alpha force back", 14)],
        createWeapon(
          "rfa-4390-armory-micro-launcher-profile",
          "Micro Launcher",
          "4-16\u201d/2",
          null,
          ["Blast (1)", "Heavy"],
          [screenshotCitation("UN Raid Force Alpha force back", 14)],
        ),
      ),
      createArmoryItem(
        "rfa-4390-armory-surge",
        "SURGE",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "EMP Only",
        [screenshotCitation("UN Raid Force Alpha force back", 14)],
        createWeapon("rfa-4390-armory-surge-profile", "Surge", "16\u201d/2", null, ["EMP Only"], [screenshotCitation("UN Raid Force Alpha force back", 14)]),
      ),
    ],
    notes: [],
    citations: [screenshotCitation("UN Raid Force Alpha force front", 13), screenshotCitation("UN Raid Force Alpha force back", 14)],
    confidence: "verified",
  };
  const booneReconForce: Force = {
    id: "boone-recon-force",
    cardId: "TFB-9860",
    name: "Boone Recon Force",
    faction: "united-martian-protectorate",
    battleDrills: [
      createTextRecord(
        "tfb-9860-battle-drill-overwhelming-fire",
        "Overwhelming Fire",
        "Return Fire Reactions that Target Models in this Unit with the Cyclic Special Rule may never roll more than 1D10.",
        [artifactCitation("Boone Recon Force battle drills", "screenshots/boone-recon-force/boone-recon-side2.png")],
      ),
      createTextRecord(
        "tfb-9860-battle-drill-small-unit-tactics",
        "Small Unit Tactics",
        "Up to half of the Models rounding up in the Unit may make the Shoot Action during the Reposition step of their Activation. This will cost them their Action during their Activation. Afterward, the remaining Models in the Unit may Reposition and then make an Action.",
        [artifactCitation("Boone Recon Force battle drills", "screenshots/boone-recon-force/boone-recon-side2.png")],
      ),
      createTextRecord(
        "tfb-9860-battle-drill-tactical-positioning",
        "Tactical Positioning",
        "During this Activation, Overwatch Targeting Models in this Unit suffers -1D10.",
        [artifactCitation("Boone Recon Force battle drills", "screenshots/boone-recon-force/boone-recon-side2.png")],
      ),
    ],
    rules: [
      createTextRecord(
        "tfb-9860-force-rule",
        "Boone Recon Force",
        "Once Per Round one non-AI or Powered Infantry Model may make the Data Attack Action.",
        [artifactCitation("Boone Recon Force rule", "screenshots/boone-recon-force/boone-recon-side2.png")],
      ),
    ],
    armory: [
      createArmoryItem(
        "tfb-9860-armory-disposable-launcher",
        "DISPOSABLE LAUNCHER",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "Blast (1)",
        [artifactCitation("Boone Recon Force armory", "screenshots/boone-recon-force/boone-recon-side2.png")],
        createWeapon("tfb-9860-armory-disposable-launcher-profile", "Disposable Launcher", "4-18”/3", null, ["Blast (1)"], [artifactCitation("Boone Recon Force armory", "screenshots/boone-recon-force/boone-recon-side2.png")]),
      ),
      createArmoryItem(
        "tfb-9860-armory-pulse-grenade",
        "PULSE GRENADE",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "EMP, Blast (1)",
        [artifactCitation("Boone Recon Force armory", "screenshots/boone-recon-force/boone-recon-side2.png")],
        createWeapon("tfb-9860-armory-pulse-grenade-profile", "Pulse Grenade", "6”/1", null, ["EMP", "Blast (1)"], [artifactCitation("Boone Recon Force armory", "screenshots/boone-recon-force/boone-recon-side2.png")]),
      ),
      createArmoryItem(
        "tfb-9860-armory-smoke-grenade",
        "SMOKE GRENADE",
        "gear",
        "UNKNOWN",
        "UNKNOWN",
        "Place a Smoke Token within 4” of a Grunt Model in this Unit before Repositioning.",
        [artifactCitation("Boone Recon Force armory", "screenshots/boone-recon-force/boone-recon-side2.png")],
      ),
      createArmoryItem(
        "tfb-9860-armory-tracking-bombs",
        "TRACKING BOMBS",
        "weapon",
        "UNKNOWN",
        "UNKNOWN",
        "AP (2), Indirect",
        [artifactCitation("Boone Recon Force armory", "screenshots/boone-recon-force/boone-recon-side2.png")],
        createWeapon("tfb-9860-armory-tracking-bombs-profile", "Tracking Bombs", "16”/1", null, ["AP (2)", "Indirect"], [artifactCitation("Boone Recon Force armory", "screenshots/boone-recon-force/boone-recon-side2.png")]),
      ),
    ],
    notes: [],
    citations: [artifactCitation("Boone Recon Force screenshot pair", "screenshots/boone-recon-force/boone-recon-side1.jpg / screenshots/boone-recon-force/boone-recon-side2.png")],
    confidence: "verified",
  };
  const manticorBorzGroup: Force = {
    id: "manticor-borz-group",
    cardId: "MBG-120",
    name: "Manticor Borz Group",
    faction: "chimera",
    battleDrills: [
      createTextRecord("mbg-120-battle-drill-linked", "Linked", "When a Model in this Unit makes the Ready Action, one Model in the Unit that has already made an Action may gain a Ready Token instead of the Model making the Action.", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")]),
      createTextRecord("mbg-120-battle-drill-targeting-smoke", "Targeting Smoke", "Place a Smoke Token within 6” of a Model in this Unit. This Unit will ignore the effects of the Smoke Token during their Activation. Enemy Units will treat the Smoke Token as normal.", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")]),
      createTextRecord("mbg-120-battle-drill-thorax-shields", "Thorax Shields", "Models in this Unit gain +1D10 for Armour Checks during this Activation.", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")]),
    ],
    rules: [createTextRecord("mbg-120-force-rule", "Manticor Borz Group Force", "Manticor Borz Group Models ignore the first point of Damage suffered from a Blast Weapon.", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")])],
    armory: [
      createArmoryItem("mbg-120-armory-air-burst-rifle", "AIR BURST RIFLE", "weapon", "UNKNOWN", "UNKNOWN", "Seeking", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")], createWeapon("mbg-120-armory-air-burst-rifle-profile", "Air Burst Rifle", "24”/1", "1", ["Seeking"], [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")])),
      createArmoryItem("mbg-120-armory-rpg33", "RPG33", "weapon", "UNKNOWN", "UNKNOWN", "Blast (1)", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")], createWeapon("mbg-120-armory-rpg33-profile", "RPG33", "16”", "4", ["Blast (1)"], [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")])),
      createArmoryItem("mbg-120-armory-strip-grenades", "STRIP GRENADES", "weapon", "UNKNOWN", "UNKNOWN", "Blast (2)", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")], createWeapon("mbg-120-armory-strip-grenades-profile", "Strip Grenades", "6”", "2", ["Blast (2)"], [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")])),
      createArmoryItem("mbg-120-armory-thermite-launcher", "THERMITE LAUNCHER", "weapon", "UNKNOWN", "UNKNOWN", "1 Shot only, Sustained (6)", [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")], createWeapon("mbg-120-armory-thermite-launcher-profile", "Thermite Launcher", "8”", "1", ["1 Shot only", "Sustained (6)"], [artifactCitation("Manticor Borz Group transcription", "docs/manticor-borz-group-transcription.md")])),
    ],
    notes: [],
    citations: [artifactCitation("Manticor Borz screenshot pair", "screenshots/manticor-borz-group/manticor-borz-side1.png / screenshots/manticor-borz-group/manticor-borz-side2.png")],
    confidence: "verified",
  };

  const units: UnitCard[] = [
    {
      id: "harlow-control-team",
      cardId: "HFR-6771",
      forceId: force.id,
      name: "Harlow Control Team",
      faction: force.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: {
        move: "4",
        skill: "6",
        armor: "1/6",
        "damage-track": 1,
      },
      specialists: [
        createSpecialist("hfr-6771-specialist-1", 1, "Data Spike", undefined, undefined, [screenshotCitation("HFR-6771 back", 4)]),
        createSpecialist(
          "hfr-6771-specialist-2",
          2,
          "Grenade Launcher",
          "Grenade Launcher | 24\u201d/2 Blast (1)",
          "Grenade Launcher",
          [screenshotCitation("HFR-6771 back", 4)],
        ),
      ],
      weapons: [
        createWeapon("hfr-6771-weapon-fal-32c", "FAL-32C", "24\u201d/1", null, ["CQB"], [screenshotCitation("HFR-6771 front", 3)]),
        createWeapon(
          "hfr-6771-weapon-grenade-launcher",
          "Grenade Launcher",
          "24\u201d/2",
          null,
          ["Blast (1)"],
          [screenshotCitation("HFR-6771 back", 4)],
          "N/A",
        ),
      ],
      abilities: [
        createTextRecord(
          "hfr-6771-control-ability",
          "Activation Control",
          "One Unit may be Activated after this Unit without spending a Control Point.",
          [screenshotCitation("HFR-6771 back", 4), ocrCitation(lines, "One Unit may be Activated after this", "OCR unit text cross-check")],
        ),
      ],
      notes: [],
      citations: [screenshotCitation("HFR-6771 front", 3), screenshotCitation("HFR-6771 back", 4)],
      confidence: "verified",
    },
    {
      id: "harlow-assault-team",
      cardId: "HFR-6772",
      forceId: force.id,
      name: "Harlow Assault Team",
      faction: force.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 2,
      stats: {
        move: "4",
        skill: "6",
        armor: "1/6",
        "damage-track": 1,
      },
      specialists: [
        createSpecialist(
          "hfr-6772-specialist-1",
          1,
          "Machine Gunner",
          "P34 | 24\u201d/1 Cyclic, Heavy",
          "P34",
          [screenshotCitation("HFR-6772 back", 6)],
        ),
        createSpecialist(
          "hfr-6772-specialist-2",
          2,
          "Team Leader",
          "When this Model gains a Ready Token it may give it to a Model in this Unit that has already made an Action.",
          undefined,
          [screenshotCitation("HFR-6772 back", 6)],
        ),
      ],
      weapons: [
        createWeapon("hfr-6772-weapon-fal-32c", "FAL-32C", "24\u201d/1", null, ["CQB"], [screenshotCitation("HFR-6772 front", 5)]),
        createWeapon(
          "hfr-6772-weapon-p34",
          "P34",
          "24\u201d/1",
          null,
          ["Cyclic", "Heavy"],
          [screenshotCitation("HFR-6772 back", 6)],
          "Machine Gunner",
        ),
      ],
      abilities: [
        createTextRecord(
          "hfr-6772-team-leader",
          "Team Leader",
          "When this Model gains a Ready Token it may give it to a Model in this Unit that has already made an Action.",
          [screenshotCitation("HFR-6772 back", 6), ocrCitation(lines, "When this Model gains a Ready Token", "OCR unit text cross-check")],
        ),
      ],
      notes: [],
      citations: [screenshotCitation("HFR-6772 front", 5), screenshotCitation("HFR-6772 back", 6)],
      confidence: "verified",
    },
    {
      id: "harlow-springbok-ai",
      cardId: "HFR-6773",
      forceId: force.id,
      name: "Harlow Springbok AI",
      faction: force.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 2,
      stats: {
        move: "6",
        skill: "6",
        armor: "2/6",
        "damage-track": 1,
      },
      specialists: [],
      weapons: [
        createWeapon(
          "hfr-6773-weapon-fal-32d",
          "FAL-32D",
          "24\u201d/1",
          null,
          ["CQB", "Sustained (1)"],
          [screenshotCitation("HFR-6773 front", 7)],
        ),
      ],
      abilities: [
        createTextRecord(
          "hfr-6773-chaff-discharge",
          "Chaff Discharge",
          "Mark a box to prevent a single Overwatch Reaction from Targeting this Model during its Activation.",
          [screenshotCitation("HFR-6773 back", 8), ocrCitation(lines, "Chaff Discharge", "OCR unit text cross-check")],
        ),
        createTextRecord(
          "hfr-6773-traits",
          "Traits",
          "AI, Jump(4)",
          [screenshotCitation("HFR-6773 back", 8), ocrCitation(lines, "AI, Jump(4)", "OCR unit text cross-check")],
        ),
      ],
      notes: [],
      citations: [screenshotCitation("HFR-6773 front", 7), screenshotCitation("HFR-6773 back", 8)],
      confidence: "verified",
    },
    {
      id: "harlow-engineers",
      cardId: "HFR-6774",
      forceId: force.id,
      name: "Harlow Engineers",
      faction: force.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: {
        move: "4",
        skill: "6",
        armor: "1/6",
        "damage-track": 1,
      },
      specialists: [
        createSpecialist(
          "hfr-6774-specialist-1",
          1,
          "Engineer",
          "AT Launcher | 8-32\u201d/3 AP (2), Blast (1)",
          "AT Launcher",
          [screenshotCitation("HFR-6774 back", 10)],
        ),
      ],
      weapons: [
        createWeapon("hfr-6774-weapon-carbine", "Carbine", "18\u201d/1", null, ["CQB"], [screenshotCitation("HFR-6774 front", 9)]),
        createWeapon(
          "hfr-6774-weapon-at-launcher",
          "AT Launcher",
          "8-32\u201d/3",
          null,
          ["AP (2)", "Blast (1)"],
          [screenshotCitation("HFR-6774 back", 10)],
          "Engineer",
        ),
      ],
      abilities: [],
      notes: [],
      citations: [screenshotCitation("HFR-6774 front", 9), screenshotCitation("HFR-6774 back", 10)],
      confidence: "verified",
    },
    {
      id: "harlow-veterans",
      cardId: "HFR-6775",
      forceId: force.id,
      name: "Harlow Veterans",
      faction: force.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 3,
      stats: {
        move: "6",
        skill: "5",
        armor: "1/6",
        "damage-track": 1,
      },
      specialists: [],
      weapons: [
        createWeapon("hfr-6775-weapon-carbine", "Carbine", "18\u201d/1", null, ["CQB"], [screenshotCitation("HFR-6775 front", 11)]),
        createWeapon("hfr-6775-weapon-machetes", "Machetes", "2\u201d/1", null, ["AP (1)", "Melee"], [screenshotCitation("HFR-6775 front", 11)]),
        createWeapon("hfr-6775-weapon-pulse-grenades", "Pulse Grenades", "6\u201d/1", null, ["Blast (1)", "EMP"], [screenshotCitation("HFR-6775 front", 11)]),
      ],
      abilities: [createTextRecord("hfr-6775-traits", "Traits", "Jump (4), Low Tech", [screenshotCitation("HFR-6775 back", 12)])],
      notes: [],
      citations: [screenshotCitation("HFR-6775 front", 11), screenshotCitation("HFR-6775 back", 12)],
      confidence: "verified",
    },
    {
      id: "harlow-crickets",
      cardId: "HFR-6776",
      forceId: force.id,
      name: "Harlow Crickets",
      faction: force.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 2,
      stats: {
        move: "6",
        skill: "7",
        armor: "1/8",
        "damage-track": 1,
      },
      specialists: [],
      weapons: [
        createWeapon("hfr-6776-weapon-self-destruct", "Self Destruct", "4\u201d/1", null, ["AP (4)", "CQB"], [screenshotCitation("HFR-6776 front", 13)]),
      ],
      abilities: [
        createTextRecord("hfr-6776-traits", "Traits", "AI, Drone", [screenshotCitation("HFR-6776 back", 14)]),
        createTextRecord(
          "hfr-6776-engineer-grouping",
          "Engineer Grouping",
          "This unit does not count toward the Unit limit when grouped with Harlow engineers, and it cannot benefit from Force Cards.",
          [screenshotCitation("HFR-6776 back", 14)],
        ),
        createTextRecord("hfr-6776-self-destruct", "Self Destruct", "Remove this model after using this weapon.", [screenshotCitation("HFR-6776 front", 13)]),
      ],
      notes: [],
      citations: [screenshotCitation("HFR-6776 front", 13), screenshotCitation("HFR-6776 back", 14)],
      confidence: "verified",
    },
    {
      id: "un-utg-assaulters",
      cardId: "RFA-4391",
      forceId: unRaidForceAlpha.id,
      name: "UN UTG Assaulters",
      faction: unRaidForceAlpha.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: {
        move: "6",
        skill: "5",
        armor: "1/5",
        "damage-track": 1,
      },
      specialists: [
        createSpecialist(
          "rfa-4391-specialist-1",
          1,
          "Grenadier",
          "Grenade Launcher | 24\u201d/2 Blast (1)",
          "Grenade Launcher",
          [screenshotCitation("RFA-4391 back", 16)],
        ),
      ],
      weapons: [
        createWeapon("rfa-4391-weapon-m7-carbine", "M7 Carbine", "18\u201d/1", null, ["CQB"], [screenshotCitation("RFA-4391 front", 15)]),
        createWeapon("rfa-4391-weapon-grenade-launcher", "Grenade Launcher", "24\u201d/2", null, ["Blast (1)"], [screenshotCitation("RFA-4391 back", 16)], "N/A"),
      ],
      abilities: [createTextRecord("rfa-4391-traits", "Traits", "Jump(4)", [screenshotCitation("RFA-4391 back", 16)])],
      notes: [],
      citations: [screenshotCitation("RFA-4391 front", 15), screenshotCitation("RFA-4391 back", 16)],
      confidence: "verified",
    },
    {
      id: "un-utg-specialists",
      cardId: "RFA-4392",
      forceId: unRaidForceAlpha.id,
      name: "UN UTG Specialists",
      faction: unRaidForceAlpha.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: {
        move: "6",
        skill: "5",
        armor: "1/5",
        "damage-track": 1,
      },
      specialists: [
        createSpecialist(
          "rfa-4392-specialist-1",
          1,
          "N/A",
          "Anti-Material Rifle | 32\u201d/2 AP (2), Deployed",
          "Anti-Material Rifle",
          [screenshotCitation("RFA-4392 back", 18)],
        ),
      ],
      weapons: [
        createWeapon("rfa-4392-weapon-m7-carbine", "M7 Carbine", "18\u201d/1", null, ["CQB"], [screenshotCitation("RFA-4392 front", 17)]),
        createWeapon(
          "rfa-4392-weapon-anti-material-rifle",
          "Anti-Material Rifle",
          "32\u201d/2",
          null,
          ["AP (2)", "Deployed"],
          [screenshotCitation("RFA-4392 back", 18)],
          "Marksman",
        ),
      ],
      abilities: [createTextRecord("rfa-4392-traits", "Traits", "Jump(4)", [screenshotCitation("RFA-4392 back", 18)])],
      notes: [],
      citations: [screenshotCitation("RFA-4392 front", 17), screenshotCitation("RFA-4392 back", 18)],
      confidence: "verified",
    },
    {
      id: "golem-unit",
      cardId: "RFA-4393",
      forceId: unRaidForceAlpha.id,
      name: "Golem Unit",
      faction: unRaidForceAlpha.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: {
        move: "4",
        skill: "5",
        armor: "3/5",
        "damage-track": 1,
      },
      specialists: [
        createSpecialist(
          "rfa-4393-specialist-1",
          1,
          "Fire Support",
          "Scorcher | 18\u201d/2 Seeking",
          "Scorcher",
          [screenshotCitation("RFA-4393 back", 20)],
        ),
      ],
      weapons: [
        createWeapon("rfa-4393-weapon-fpr-auto", "FPR Auto", "24\u201d/1", null, ["Sustained (1)"], [screenshotCitation("RFA-4393 front", 19)]),
        createWeapon("rfa-4393-weapon-scorcher", "Scorcher", "18\u201d/2", null, ["Seeking"], [screenshotCitation("RFA-4393 back", 20)], "N/A"),
      ],
      abilities: [createTextRecord("rfa-4393-traits", "Traits", "Jump(4)", [screenshotCitation("RFA-4393 back", 20)])],
      notes: [],
      citations: [screenshotCitation("RFA-4393 front", 19), screenshotCitation("RFA-4393 back", 20)],
      confidence: "verified",
    },
    {
      id: "boone-vat-element",
      cardId: "TFB-9862",
      forceId: booneReconForce.id,
      name: "Boone VAT Element",
      faction: booneReconForce.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: { move: "6", skill: "6", armor: "1/6", "damage-track": 1 },
      specialists: [
        createSpecialist("tfb-9862-specialist-1", 1, "Data Specialist", "Jammer | 12”, Data Knife | 6”", "Jammer", [artifactCitation("Boone VAT Element specialists", "screenshots/boone-recon-force/boone-recon-side2.png")]),
        createSpecialist("tfb-9862-specialist-2", 2, "SAW Gunner", "Compact LMG | 24”/1 Cyclic, CQB", "Compact LMG", [artifactCitation("Boone VAT Element specialists", "screenshots/boone-recon-force/boone-recon-side2.png")]),
      ],
      weapons: [
        createWeapon("tfb-9862-weapon-carbine", "Carbine", "18”/1", null, ["CQB"], [artifactCitation("Boone VAT Element front", "screenshots/boone-recon-force/boone-recon-side1.jpg")]),
        createWeapon("tfb-9862-weapon-jammer", "Jammer", "12”", null, [], [artifactCitation("Boone VAT Element specialists", "screenshots/boone-recon-force/boone-recon-side2.png")], "Data Specialist"),
        createWeapon("tfb-9862-weapon-data-knife", "Data Knife", "6”", null, [], [artifactCitation("Boone VAT Element specialists", "screenshots/boone-recon-force/boone-recon-side2.png")], "Data Specialist"),
        createWeapon("tfb-9862-weapon-compact-lmg", "Compact LMG", "24”/1", null, ["Cyclic", "CQB"], [artifactCitation("Boone VAT Element specialists", "screenshots/boone-recon-force/boone-recon-side2.png")], "SAW Gunner"),
      ],
      abilities: [createTextRecord("tfb-9862-traits", "Traits", "Jump (4)", [artifactCitation("Boone VAT Element", "screenshots/boone-recon-force/boone-recon-side2.png")])],
      notes: [],
      citations: [artifactCitation("Boone VAT Element screenshot pair", "screenshots/boone-recon-force/boone-recon-side1.jpg / screenshots/boone-recon-force/boone-recon-side2.png")],
      confidence: "verified",
    },
    {
      id: "boone-recon-team",
      cardId: "TFB-9861",
      forceId: booneReconForce.id,
      name: "Boone Recon Team",
      faction: booneReconForce.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 2,
      stats: { move: "6", skill: "4", armor: "1/6", "damage-track": 1 },
      specialists: [
        createSpecialist("tfb-9861-specialist-1", 1, "Team Leader", "When this Model would gain a Ready Token from the Ready Action, it may instead give it to a Model in the Unit that has already made an Action.", undefined, [artifactCitation("Boone Recon Team specialists", "screenshots/boone-recon-force/boone-recon-side2.png")]),
        createSpecialist("tfb-9861-specialist-2", 2, "SAW Gunner", "LMG | 32”/1 Cyclic, Heavy", "LMG", [artifactCitation("Boone Recon Team specialists", "screenshots/boone-recon-force/boone-recon-side2.png")]),
      ],
      weapons: [
        createWeapon("tfb-9861-weapon-heavy-rifle", "Heavy Rifle", "24”/1", null, [], [artifactCitation("Boone Recon Team front", "screenshots/boone-recon-force/boone-recon-side1.jpg")]),
        createWeapon("tfb-9861-weapon-lmg", "LMG", "32”/1", null, ["Cyclic", "Heavy"], [artifactCitation("Boone Recon Team specialists", "screenshots/boone-recon-force/boone-recon-side2.png")], "SAW Gunner"),
      ],
      abilities: [createTextRecord("tfb-9861-team-leader", "Team Leader", "When this Model would gain a Ready Token from the Ready Action, it may instead give it to a Model in the Unit that has already made an Action.", [artifactCitation("Boone Recon Team specialists", "screenshots/boone-recon-force/boone-recon-side2.png")])],
      notes: [],
      citations: [artifactCitation("Boone Recon Team screenshot pair", "screenshots/boone-recon-force/boone-recon-side1.jpg / screenshots/boone-recon-force/boone-recon-side2.png")],
      confidence: "verified",
    },
    {
      id: "boone-razorback",
      cardId: "TFB-9863",
      forceId: booneReconForce.id,
      name: "Boone Razorback",
      faction: booneReconForce.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: { move: "5", skill: "4", armor: "3/4", "damage-track": 1 },
      specialists: [],
      weapons: [
        createWeapon("tfb-9863-weapon-gauss-saw", "Gauss SAW", "32”/1", null, ["Cyclic", "AP (2)", "Auto (2)"], [artifactCitation("Boone Razorback front", "screenshots/boone-recon-force/boone-recon-side1.jpg")]),
        createWeapon("tfb-9863-weapon-razorback-atgm", "Razorback ATGM", "6-32”/2", null, ["Blast (1)", "Indirect"], [artifactCitation("Boone Razorback front", "screenshots/boone-recon-force/boone-recon-side1.jpg")]),
      ],
      abilities: [createTextRecord("tfb-9863-traits", "Traits", "Drone, AI, Damage Track", [artifactCitation("Boone Razorback", "screenshots/boone-recon-force/boone-recon-side2.png")])],
      notes: [],
      citations: [artifactCitation("Boone Razorback screenshot pair", "screenshots/boone-recon-force/boone-recon-side1.jpg / screenshots/boone-recon-force/boone-recon-side2.png")],
      confidence: "verified",
    },
    {
      id: "boone-control-team",
      cardId: "TFB-9864",
      forceId: booneReconForce.id,
      name: "Boone Control Team",
      faction: booneReconForce.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: { move: "5", skill: "6", armor: "1/6", "damage-track": 1 },
      specialists: [
        createSpecialist("tfb-9864-specialist-1", 1, "Data Specialist", "Data Specialist", "N/A", [artifactCitation("Boone Control Team summary", "screenshots/extraction-progress.md")]),
        createSpecialist("tfb-9864-specialist-2", 2, "Grenadier", "Grenadier", "N/A", [artifactCitation("Boone Control Team summary", "screenshots/extraction-progress.md")]),
      ],
      weapons: [createWeapon("tfb-9864-weapon-carbine", "Carbine", "18”/1", null, [], [artifactCitation("Boone Control Team summary", "screenshots/extraction-progress.md")])],
      abilities: [createTextRecord("tfb-9864-activation-control", "Activation Control", "One Unit may be Activated after this Unit without spending a Control Point.", [artifactCitation("Boone Control Team summary", "screenshots/extraction-progress.md")]), createTextRecord("tfb-9864-traits", "Traits", "Jump (4)", [artifactCitation("Boone Control Team summary", "screenshots/extraction-progress.md")])],
      notes: [],
      citations: [artifactCitation("Boone Control Team screenshot", "screenshots/boone-recon-force/boone-control-team.png")],
      confidence: "verified",
    },
    {
      id: "boone-marksman-team",
      cardId: "TFB-9865",
      forceId: booneReconForce.id,
      name: "Boone Marksman Team",
      faction: booneReconForce.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: { move: "5", skill: "6", armor: "1/6", "damage-track": 1 },
      specialists: [createSpecialist("tfb-9865-specialist-1", 1, "Marksman", "Marksman (AMR)", "AMR", [artifactCitation("Boone Marksman Team summary", "screenshots/extraction-progress.md")])],
      weapons: [createWeapon("tfb-9865-weapon-carbine", "Carbine", "18”/1", null, [], [artifactCitation("Boone Marksman Team summary", "screenshots/extraction-progress.md")]), createWeapon("tfb-9865-weapon-amr", "AMR", "UNKNOWN", null, [], [artifactCitation("Boone Marksman Team summary", "screenshots/extraction-progress.md")], "Marksman")],
      abilities: [createTextRecord("tfb-9865-traits", "Traits", "Jump (4)", [artifactCitation("Boone Marksman Team summary", "screenshots/extraction-progress.md")])],
      notes: [],
      citations: [artifactCitation("Boone Marksman Team screenshot", "screenshots/boone-recon-force/boone-marksman-team.png")],
      confidence: "verified",
    },
    {
      id: "boone-spt",
      cardId: "TFB-9866",
      forceId: booneReconForce.id,
      name: "Boone SPT",
      faction: booneReconForce.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 1,
      stats: { move: "5", skill: "4", armor: "3/4", "damage-track": 1 },
      specialists: [createSpecialist("tfb-9866-specialist-1", 1, "Fire Support", "Fire Support (Scorcher)", "Scorcher", [artifactCitation("Boone SPT summary", "screenshots/extraction-progress.md")])],
      weapons: [createWeapon("tfb-9866-weapon-fpr-auto", "FPR Auto", "UNKNOWN", null, [], [artifactCitation("Boone SPT summary", "screenshots/extraction-progress.md")]), createWeapon("tfb-9866-weapon-scorcher", "Scorcher", "UNKNOWN", null, [], [artifactCitation("Boone SPT summary", "screenshots/extraction-progress.md")], "Fire Support")],
      abilities: [createTextRecord("tfb-9866-traits", "Traits", "Jump (4)", [artifactCitation("Boone SPT summary", "screenshots/extraction-progress.md")])],
      notes: [],
      citations: [artifactCitation("Boone SPT screenshot", "screenshots/boone-recon-force/boone-spt.png")],
      confidence: "verified",
    },
    {
      id: "manticor-bratva-team",
      cardId: "MBG-122",
      forceId: manticorBorzGroup.id,
      name: "Manticor Bratva Team",
      faction: manticorBorzGroup.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 2,
      stats: { move: "4", skill: "6", armor: "1/4", "damage-track": 1 },
      specialists: [createSpecialist("mbg-122-specialist-1", 1, "Data Spike", "N/A", "N/A", [artifactCitation("Manticor Bratva transcription", "docs/manticor-borz-group-transcription.md")]), createSpecialist("mbg-122-specialist-2", 2, "HMG", "Shield, HMG | 4-24”/2 Sustained (2), Deployed", "HMG", [artifactCitation("Manticor Bratva transcription", "docs/manticor-borz-group-transcription.md")])],
      weapons: [createWeapon("mbg-122-weapon-akmz-2", "AKMZ-2", "24”", "1", ["Medium"], [artifactCitation("Manticor Bratva transcription", "docs/manticor-borz-group-transcription.md")]), createWeapon("mbg-122-weapon-hmg", "HMG", "4-24”/2", null, ["Sustained (2)", "Deployed"], [artifactCitation("Manticor Bratva transcription", "docs/manticor-borz-group-transcription.md")], "HMG")],
      abilities: [createTextRecord("mbg-122-shield", "Shield", "Shield", [artifactCitation("Manticor Bratva transcription", "docs/manticor-borz-group-transcription.md")]), createTextRecord("mbg-122-initiative", "Initiative", "If at least two Models from this Unit are on the Table, you may roll an additional D10 for Initiative. Use the highest result rolled.", [artifactCitation("Manticor Bratva transcription", "docs/manticor-borz-group-transcription.md")])],
      notes: [],
      citations: [artifactCitation("Manticor Bratva screenshot pair", "screenshots/manticor-borz-group/manticor-borz-side1.png / screenshots/manticor-borz-group/manticor-borz-side2.png")],
      confidence: "verified",
    },
    {
      id: "manticor-cyka-team",
      cardId: "MBG-123",
      forceId: manticorBorzGroup.id,
      name: "Manticor Cyka Team",
      faction: manticorBorzGroup.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 2,
      stats: { move: "4", skill: "6", armor: "2/4", "damage-track": 2 },
      specialists: [],
      weapons: [createWeapon("mbg-123-weapon-syy-1", "SYY-1", "24”", "1", ["Cyclic", "Heavy"], [artifactCitation("Manticor Cyka transcription", "docs/manticor-borz-group-transcription.md")]), createWeapon("mbg-123-weapon-grenade-launcher", "Grenade Launcher", "24”/2", "N/A", ["Blast (1)"], [artifactCitation("Manticor Cyka transcription", "docs/manticor-borz-group-transcription.md")])],
      abilities: [],
      notes: [],
      citations: [artifactCitation("Manticor Cyka screenshot pair", "screenshots/manticor-borz-group/manticor-borz-side1.png / screenshots/manticor-borz-group/manticor-borz-side2.png")],
      confidence: "verified",
    },
    {
      id: "manticor-insertion-team",
      cardId: "MBG-121",
      forceId: manticorBorzGroup.id,
      name: "Manticor Insertion Team",
      faction: manticorBorzGroup.faction,
      unitType: "UNKNOWN",
      role: "UNKNOWN",
      cost: "UNKNOWN",
      grunts: 2,
      stats: { move: "4", skill: "6", armor: "1/4", "damage-track": 1 },
      specialists: [createSpecialist("mbg-121-specialist-1", 1, "Machine Gunner", "SYY-1 | 24”/1 Cyclic, Heavy", "SYY-1", [artifactCitation("Manticor Insertion transcription", "docs/manticor-borz-group-transcription.md")]), createSpecialist("mbg-121-specialist-2", 2, "Sidewinder", "Sidewinder (2 uses) | Check one of these boxes to allow this Model to use its Action to make a Skill Check. If it passes, you may give a Unit with a Model within 12” of this Model a Pinned Marker.", "N/A", [artifactCitation("Manticor Insertion transcription", "docs/manticor-borz-group-transcription.md")])],
      weapons: [createWeapon("mbg-121-weapon-akmz-2", "AKMZ-2", "24”", "1", ["Medium"], [artifactCitation("Manticor Insertion transcription", "docs/manticor-borz-group-transcription.md")]), createWeapon("mbg-121-weapon-syy-1", "SYY-1", "24”/1", null, ["Cyclic", "Heavy"], [artifactCitation("Manticor Insertion transcription", "docs/manticor-borz-group-transcription.md")], "Machine Gunner")],
      abilities: [createTextRecord("mbg-121-sidewinder", "Sidewinder", "Sidewinder (2 uses) | Check one of these boxes to allow this Model to use its Action to make a Skill Check. If it passes, you may give a Unit with a Model within 12” of this Model a Pinned Marker.", [artifactCitation("Manticor Insertion transcription", "docs/manticor-borz-group-transcription.md")])],
      notes: [],
      citations: [artifactCitation("Manticor Insertion screenshot pair", "screenshots/manticor-borz-group/manticor-borz-side1.png / screenshots/manticor-borz-group/manticor-borz-side2.png")],
      confidence: "verified",
    },
  ];

  return {
    forceDataset: {
      meta: {
        kind: "forces",
        version: "packet-7",
        generatedAt: options.generatedAt,
        sourceDocumentIds: [UNIT_CARD_DOCUMENT_ID, SCREENSHOT_DOCUMENT_ID],
        confidence: "verified",
      },
      data: {
        forces: [force, unRaidForceAlpha, booneReconForce, manticorBorzGroup],
        units,
      },
    },
    auditDataset: {
      meta: {
        kind: "force-audit",
        version: "packet-7",
        generatedAt: options.generatedAt,
        sourceDocumentIds: [UNIT_CARD_DOCUMENT_ID, SCREENSHOT_DOCUMENT_ID],
        confidence: "raw",
      },
      data: {
        rawCards: [
          createRawCard(lines, "HFR-6770", "Harlow 1st Reaction Force", "force", 1, 68, "OCR retained for audit only. All curated force fields verified against screenshots side1 and side2."),
          createRawCard(lines, "HFR-6771", "Harlow Control Team", "unit", 49, 68, "OCR retained for audit only. Stats, weapon, specialists, and rules verified against screenshots side1 and side2."),
          createRawCard(lines, "HFR-6772", "Harlow Assault Team", "unit", 49, 68, "OCR retained for audit only. Stats, weapon, specialists, and rules verified against screenshots side1 and side2."),
          createRawCard(lines, "HFR-6773", "Harlow Springbok AI", "unit", 49, 68, "OCR retained for audit only. Stats, weapon, and abilities verified against screenshots side1 and side2."),
          createScreenshotRawCard("HFR-6774", "Harlow Engineers", "unit", "screenshots/harlow-1st-reaction/harlow-team2-side1.png", "screenshots/harlow-1st-reaction/harlow-team2-side2.png"),
          createScreenshotRawCard("HFR-6775", "Harlow Veterans", "unit", "screenshots/harlow-1st-reaction/harlow-team2-side1.png", "screenshots/harlow-1st-reaction/harlow-team2-side2.png"),
          createScreenshotRawCard("HFR-6776", "Harlow Crickets", "unit", "screenshots/harlow-1st-reaction/harlow-team2-side1.png", "screenshots/harlow-1st-reaction/harlow-team2-side2.png"),
          createScreenshotRawCard("RFA-4390", "UN Raid Force Alpha", "force", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side1.jpg", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side2.png"),
          createScreenshotRawCard("RFA-4391", "UN UTG Assaulters", "unit", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side1.jpg", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side2.png"),
          createScreenshotRawCard("RFA-4392", "UN UTG Specialists", "unit", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side1.jpg", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side2.png"),
          createScreenshotRawCard("RFA-4393", "Golem Unit", "unit", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side1.jpg", "screenshots/un-raidforce-alpha/un-raidforce-alpha-side2.png"),
          createScreenshotRawCard("TFB-9860", "Boone Recon Force", "force", "screenshots/boone-recon-force/boone-recon-side1.jpg", "screenshots/boone-recon-force/boone-recon-side2.png"),
          createScreenshotRawCard("TFB-9861", "Boone Recon Team", "unit", "screenshots/boone-recon-force/boone-recon-side1.jpg", "screenshots/boone-recon-force/boone-recon-side2.png"),
          createScreenshotRawCard("TFB-9862", "Boone VAT Element", "unit", "screenshots/boone-recon-force/boone-recon-side1.jpg", "screenshots/boone-recon-force/boone-recon-side2.png"),
          createScreenshotRawCard("TFB-9863", "Boone Razorback", "unit", "screenshots/boone-recon-force/boone-recon-side1.jpg", "screenshots/boone-recon-force/boone-recon-side2.png"),
          createScreenshotRawCard("TFB-9864", "Boone Control Team", "unit", "screenshots/boone-recon-force/boone-control-team.png", "screenshots/boone-recon-force/boone-control-team.png"),
          createScreenshotRawCard("TFB-9865", "Boone Marksman Team", "unit", "screenshots/boone-recon-force/boone-marksman-team.png", "screenshots/boone-recon-force/boone-marksman-team.png"),
          createScreenshotRawCard("TFB-9866", "Boone SPT", "unit", "screenshots/boone-recon-force/boone-spt.png", "screenshots/boone-recon-force/boone-spt.png"),
          createScreenshotRawCard("MBG-120", "Manticor Borz Group", "force", "screenshots/manticor-borz-group/manticor-borz-side1.png", "screenshots/manticor-borz-group/manticor-borz-side2.png"),
          createScreenshotRawCard("MBG-121", "Manticor Insertion Team", "unit", "screenshots/manticor-borz-group/manticor-borz-side1.png", "screenshots/manticor-borz-group/manticor-borz-side2.png"),
          createScreenshotRawCard("MBG-122", "Manticor Bratva Team", "unit", "screenshots/manticor-borz-group/manticor-borz-side1.png", "screenshots/manticor-borz-group/manticor-borz-side2.png"),
          createScreenshotRawCard("MBG-123", "Manticor Cyka Team", "unit", "screenshots/manticor-borz-group/manticor-borz-side1.png", "screenshots/manticor-borz-group/manticor-borz-side2.png"),
        ],
      },
    },
  };
}

function artifactCitation(label: string, excerpt: string, sectionId?: string): SourceCitation {
  return {
    documentId: SCREENSHOT_DOCUMENT_ID,
    label,
    sectionId,
    excerpt,
  };
}

function createTextRecord(id: string, name: string, text: string, citations: SourceCitation[]): CitationBackedText {
  return { id, name, text, citations };
}

function createArmoryItem(
  id: string,
  name: string,
  type: string,
  cost: string,
  restrictions: string,
  text: string,
  citations: SourceCitation[],
  weapon?: WeaponProfile,
): ArmoryItem {
  return { id, name, type, cost, restrictions, text, weapon, citations };
}

function createWeapon(
  id: string,
  name: string,
  range: string,
  damage: string | null,
  traits: string[],
  citations: SourceCitation[],
  carrier?: string,
): WeaponProfile {
  return { id, name, range, damage, traits, citations, carrier };
}

function createSpecialist(
  id: string,
  slot: number,
  name: string,
  description: string | undefined,
  weapon: string | undefined,
  citations: SourceCitation[],
): UnitSpecialist {
  return { id, slot, name, description, weapon, citations };
}

function screenshotCitation(label: string, screenshotNumber: number): SourceCitation {
  return {
    documentId: SCREENSHOT_DOCUMENT_ID,
    label,
    sectionId: `screenshot-${screenshotNumber}`,
    excerpt: `Verified against Packet 3 screenshot ${screenshotNumber}`,
  };
}

function ocrCitation(lines: string[], exactLine: string, label: string): SourceCitation {
  const lineIndex = lines.findIndex((line) => line.includes(exactLine));

  return {
    documentId: UNIT_CARD_DOCUMENT_ID,
    label,
    lineStart: lineIndex >= 0 ? lineIndex + 1 : undefined,
    lineEnd: lineIndex >= 0 ? lineIndex + 1 : undefined,
    excerpt: lineIndex >= 0 ? lines[lineIndex] : exactLine,
  };
}

function createRawCard(
  lines: string[],
  cardId: string,
  name: string,
  recordType: "force" | "unit",
  startLine: number,
  endLine: number,
  notes: string,
) {
  return {
    id: `${cardId.toLowerCase()}-raw`,
    cardId,
    name,
    recordType,
    rawLines: lines.slice(startLine - 1, endLine),
    verificationDocumentIds: [SCREENSHOT_DOCUMENT_ID],
    notes,
    citations: [
      {
        documentId: UNIT_CARD_DOCUMENT_ID,
        label: `${cardId} OCR excerpt`,
        lineStart: startLine,
        lineEnd: endLine,
      },
    ],
  };
}

function createScreenshotRawCard(cardId: string, name: string, recordType: "force" | "unit", frontFile: string, backFile: string) {
  return {
    id: `${cardId.toLowerCase()}-raw`,
    cardId,
    name,
    recordType,
    rawLines: [`Front screenshot: ${frontFile}`, `Back screenshot: ${backFile}`],
    verificationDocumentIds: [SCREENSHOT_DOCUMENT_ID],
    notes: "Curated directly from screenshots; no OCR markdown source is available for this card yet.",
    citations: [
      {
        documentId: SCREENSHOT_DOCUMENT_ID,
        label: `${cardId} screenshot pair`,
        excerpt: `${frontFile} / ${backFile}`,
      },
    ],
  };
}
