import type { RouteManifestEntry } from "@/lib/types/domain";

export const appRouteManifest: RouteManifestEntry[] = [
  {
    id: "home",
    path: "/",
    label: "Home Hub",
    shortLabel: "Home",
    section: "Hub",
    summary: "Recent work, source registry status, and the preferred first vertical slice.",
    activationPacket: 0,
    dataContracts: ["SourceDocument", "RouteManifestEntry"],
    nav: true,
  },
  {
    id: "lore",
    path: "/lore",
    label: "Lore",
    shortLabel: "Lore",
    section: "Reference",
    summary: "World guide hub for timeline, factions, settlements, flora, and fauna.",
    activationPacket: 4,
    dataContracts: ["LoreEvent", "LoreFaction", "LoreLocation", "LoreSpecies", "GlossaryTerm"],
    nav: true,
  },
  {
    id: "timeline",
    path: "/lore/timeline",
    label: "Timeline",
    shortLabel: "Timeline",
    section: "Reference",
    summary: "Interactive chronology of ABOL and major wars.",
    activationPacket: 4,
    dataContracts: ["LoreEvent"],
    nav: false,
  },
  {
    id: "lore-faction-detail",
    path: "/lore/factions/:slug",
    label: "Lore Faction Detail",
    shortLabel: "Faction",
    section: "Reference",
    summary: "Detailed lore pages for factions and their related playable forces.",
    activationPacket: 4,
    dataContracts: ["LoreFaction", "Force"],
    nav: false,
  },
  {
    id: "forces",
    path: "/forces",
    label: "Forces",
    shortLabel: "Forces",
    section: "Reference",
    summary: "Playable force browser and seed slice access point.",
    activationPacket: 4,
    dataContracts: ["Force"],
    nav: true,
  },
  {
    id: "force-detail",
    path: "/forces/:forceId",
    label: "Force Detail",
    shortLabel: "Force",
    section: "Reference",
    summary: "Force rule, battle drills, armory, and related units.",
    activationPacket: 4,
    dataContracts: ["Force", "UnitCard", "EffectiveRuleRecord"],
    nav: false,
  },
  {
    id: "unit-detail",
    path: "/units/:unitId",
    label: "Unit Detail",
    shortLabel: "Unit",
    section: "Reference",
    summary: "Curated unit card view with effective rules and citations.",
    activationPacket: 4,
    dataContracts: ["UnitCard", "WeaponProfile", "EffectiveRuleRecord"],
    nav: false,
  },
  {
    id: "rules",
    path: "/rules",
    label: "Rules",
    shortLabel: "Rules",
    section: "Reference",
    summary: "Rules landing page for mode filters, lookup, FAQ, and errata.",
    activationPacket: 4,
    dataContracts: ["RuleSection", "EffectiveRuleRecord", "FaqEntry", "ErrataEntry"],
    nav: true,
  },
  {
    id: "rules-core",
    path: "/rules/core",
    label: "Core Rules",
    shortLabel: "Core Rules",
    section: "Reference",
    summary: "Core rulebook browser with effective text overlays.",
    activationPacket: 4,
    dataContracts: ["RuleSection", "EffectiveRuleRecord"],
    nav: false,
  },
  {
    id: "rules-matched-play",
    path: "/rules/matched-play",
    label: "Matched Play Rules",
    shortLabel: "Matched",
    section: "Reference",
    summary: "Matched play overlay and supplemental clarifications.",
    activationPacket: 7,
    dataContracts: ["RuleSection", "EffectiveRuleRecord", "FaqEntry", "ErrataEntry"],
    nav: false,
  },
  {
    id: "usr-detail",
    path: "/rules/usr/:slug",
    label: "USR Detail",
    shortLabel: "USR",
    section: "Reference",
    summary: "Universal special rule details and linked entities.",
    activationPacket: 4,
    dataContracts: ["UniversalSpecialRule", "EffectiveRuleRecord"],
    nav: false,
  },
  {
    id: "scenarios",
    path: "/scenarios",
    label: "Scenarios",
    shortLabel: "Scenarios",
    section: "Reference",
    summary: "Scenario browser with setup, scoring, and special-rule filters.",
    activationPacket: 4,
    dataContracts: ["Scenario"],
    nav: true,
  },
  {
    id: "scenario-detail",
    path: "/scenarios/:scenarioId",
    label: "Scenario Detail",
    shortLabel: "Scenario",
    section: "Reference",
    summary: "Scenario setup and scoring details with citations.",
    activationPacket: 4,
    dataContracts: ["Scenario", "EffectiveRuleRecord"],
    nav: false,
  },
  {
    id: "builder",
    path: "/builder",
    label: "Builder",
    shortLabel: "Builder",
    section: "Play",
    summary: "Roster and group builder reserved for legality workflows and local saves.",
    activationPacket: 5,
    dataContracts: ["Roster", "Force", "UnitCard"],
    nav: true,
  },
  {
    id: "matches",
    path: "/matches",
    label: "Matches",
    shortLabel: "Matches",
    section: "Play",
    summary: "Saved matches and match setup for the seed slice tracker.",
    activationPacket: 6,
    dataContracts: ["Match", "Roster", "Scenario"],
    nav: true,
  },
  {
    id: "match-detail",
    path: "/matches/:matchId",
    label: "Match Detail",
    shortLabel: "Tracker",
    section: "Play",
    summary: "Live match tracker reserved for round flow, activations, and scoring.",
    activationPacket: 6,
    dataContracts: ["Match", "UnitState", "TokenState"],
    nav: false,
  },
  {
    id: "glossary",
    path: "/glossary",
    label: "Glossary",
    shortLabel: "Glossary",
    section: "Reference",
    summary: "Acronyms, abbreviations, and keyword cross-links.",
    activationPacket: 4,
    dataContracts: ["GlossaryTerm"],
    nav: true,
  },
];

export const primaryNavigation = appRouteManifest.filter((route) => route.nav);

export function getRouteManifestEntry(routeId: string) {
  return appRouteManifest.find((route) => route.id === routeId);
}
